name: Deploy Application
on: 
  workflow_dispatch:
    inputs:
      image_name:
        description: 'image name'
        type: string
        required: true
      image_version:
        description: 'image version'
        type: string
        required: true
      artifactory_path:
        description: 'artifactory path'
        type: string
        required: true

jobs:
  deploy:
    concurrency: deploy
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'
